---
title: "p8105_hw1_lj2607"
output: github_document
date: "2024-09-21"
---

Problem 1

```{r}
#load dataset penguis

data("penguins", package = "palmerpenguins")
```

```{r}
#check the first 5 rows in data

head(penguins,10)
```


```{r}
#check the size of dataset

nrow(penguins)
ncol(penguins)
```

```{r}
#list valuable variable in th dataset

penguins = janitor::clean_names(penguins)
names(penguins)

```

```{r}
#calculate the mean flipper length after cleaning NA values
mean_flipper_length <- mean(penguins$flipper_length_mm, na.rm = TRUE)

# Print the result
mean_flipper_length
```

```{r}
# check the summary of dataset
summary(penguins)
```

The penguins dataset includes 344 observations across three species (Adelie, Chinstrap, and Gentoo) from three islands (Biscoe, Dream, and Torgersen) collected between 2007 and 2009. Key measurements include bill length (ranging from 32.1 mm to 59.6 mm), bill depth (13.1 mm to 21.5 mm), flipper length (172 mm to 231 mm with mean equal to 200.9), and body mass (2700 g to 6300 g). There are some missing values in the dataset.