p8105_hw1_lj2607
================
2024-09-21

Problem 1

``` r
#load dataset penguis

data("penguins", package = "palmerpenguins")
```

``` r
#check the first 5 rows in data

head(penguins,10)
```

    ## # A tibble: 10 × 8
    ##    species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
    ##    <fct>   <fct>              <dbl>         <dbl>             <int>       <int>
    ##  1 Adelie  Torgersen           39.1          18.7               181        3750
    ##  2 Adelie  Torgersen           39.5          17.4               186        3800
    ##  3 Adelie  Torgersen           40.3          18                 195        3250
    ##  4 Adelie  Torgersen           NA            NA                  NA          NA
    ##  5 Adelie  Torgersen           36.7          19.3               193        3450
    ##  6 Adelie  Torgersen           39.3          20.6               190        3650
    ##  7 Adelie  Torgersen           38.9          17.8               181        3625
    ##  8 Adelie  Torgersen           39.2          19.6               195        4675
    ##  9 Adelie  Torgersen           34.1          18.1               193        3475
    ## 10 Adelie  Torgersen           42            20.2               190        4250
    ## # ℹ 2 more variables: sex <fct>, year <int>

``` r
#check the size of dataset

nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
#list valuable variable in th dataset

penguins = janitor::clean_names(penguins)
names(penguins)
```

    ## [1] "species"           "island"            "bill_length_mm"   
    ## [4] "bill_depth_mm"     "flipper_length_mm" "body_mass_g"      
    ## [7] "sex"               "year"

``` r
#calculate the mean flipper length after cleaning NA values
mean_flipper_length <- mean(penguins$flipper_length_mm, na.rm = TRUE)

# Print the result
mean_flipper_length
```

    ## [1] 200.9152

``` r
# check the summary of dataset
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

The penguins dataset includes 344 observations rows and 8 columns across
three species (Adelie, Chinstrap, and Gentoo) from three islands
(Biscoe, Dream, and Torgersen) collected between 2007 and 2009. Key
measurements include sex, bill length (ranging from 32.1 mm to 59.6 mm),
bill depth (13.1 mm to 21.5 mm), flipper length (172 mm to 231 mm with
mean equal to 200.9), and body mass (2700 g to 6300 g). There are some
missing values in the dataset.

``` r
#load package ggplot2
library(ggplot2)

#make a scatterplot with X as bill_length_mm and Y as flipper_length_mm and color points using Species variable
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

![](p8105_hw1_lj2607_files/figure-gfm/unnamed-chunk-7-1.png)<!-- -->

``` r
ggsave("scatterplot_penguins.png")
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).
